#!/usr/bin/env python3
"""Recompute integrity hashes for every example bundle, killing placeholders.

Per AGENTS.md, example hashes are generated by tooling (never hand-edited) and
placeholder hashes are a defect. This resolves every ``EXAMPLE-HASH-*``
placeholder to a real SHA-256 (RFC 8785) value in dependency order — request
envelopes first, then anything that references them — and writes the results
back into the raw file text so existing formatting is preserved.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from ztap.hashing import envelope_hash  # noqa: E402

PLACEHOLDER_PREFIX = "EXAMPLE-HASH-"


def illustrative_hash(descriptor: str) -> str:
    """A real, deterministic SHA-256 for a reference to content outside the bundle.

    Some example envelopes reference hashes of non-envelope content (external
    evidence files, actor-registry state snapshots, or child envelopes omitted
    for brevity). Those cannot be the hash of any envelope present, so we give
    them a recomputable illustrative digest of their descriptor rather than
    leaving a placeholder (a defect per AGENTS.md). Examples already declare
    their hashes illustrative via ``draft_notice``.
    """
    return hashlib.sha256(descriptor.encode("utf-8")).hexdigest()


def find_placeholders(obj) -> set[str]:
    found: set[str] = set()

    def walk(node) -> None:
        if isinstance(node, str):
            if node.startswith(PLACEHOLDER_PREFIX):
                found.add(node)
        elif isinstance(node, dict):
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(obj)
    return found


def substitute(obj, mapping: dict[str, str]):
    if isinstance(obj, str):
        return mapping.get(obj, obj)
    if isinstance(obj, dict):
        return {key: substitute(value, mapping) for key, value in obj.items()}
    if isinstance(obj, list):
        return [substitute(value, mapping) for value in obj]
    return obj


def resolve_bundle(bundle: dict) -> tuple[dict[str, str], list]:
    """Return (placeholder -> real hash, list of unresolved placeholders)."""
    envelopes = bundle.get("envelopes", [])
    resolved: dict[str, str] = {}

    # References to content outside the bundle (external evidence, state
    # snapshots, omitted child envelopes) are not the hash of any envelope
    # present. Seed them with a deterministic illustrative digest so the
    # remaining in-bundle envelopes can seal.
    own_placeholders = {
        (env.get("integrity") or {}).get("hash_value")
        for env in envelopes
    }
    own_placeholders = {
        value for value in own_placeholders
        if isinstance(value, str) and value.startswith(PLACEHOLDER_PREFIX)
    }
    for reference in find_placeholders(bundle) - own_placeholders:
        resolved[reference] = illustrative_hash(reference)

    unsealed = list(envelopes)
    progress = True
    while unsealed and progress:
        progress = False
        for env in list(unsealed):
            own = (env.get("integrity") or {}).get("hash_value")
            external = find_placeholders(env) - ({own} if own else set())
            if external <= set(resolved):
                sealed = substitute(env, resolved)
                digest = envelope_hash(sealed)
                if isinstance(own, str) and own.startswith(PLACEHOLDER_PREFIX):
                    resolved[own] = digest
                unsealed.remove(env)
                progress = True
    unresolved = [(env.get("integrity") or {}).get("hash_value") for env in unsealed]
    return resolved, unresolved


def main() -> int:
    examples_dir = REPO_ROOT / "examples"
    total = 0
    for path in sorted(examples_dir.glob("*.json")):
        bundle = json.loads(path.read_text(encoding="utf-8"))
        mapping, unresolved = resolve_bundle(bundle)
        if unresolved:
            print(f"WARN {path.name}: unresolved placeholders: {unresolved}")
        text = path.read_text(encoding="utf-8")
        replaced = 0
        for placeholder, real in sorted(mapping.items(), key=lambda kv: -len(kv[0])):
            occurrences = text.count(placeholder)
            if occurrences:
                text = text.replace(placeholder, real)
                replaced += occurrences
        path.write_text(text, encoding="utf-8")
        total += replaced
        print(f"{path.name}: {replaced} replacement(s) across {len(mapping)} hash(es)")
    print(f"\nDone: {total} total placeholder replacement(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
